export class Events {
    static SETTINGS_TRANSLATE_CLIPBOARD_SHORTCUT_CHANGE: string = 'SETTINGS_TRANSLATE_CLIPBOARD_SHORTCUT_CHANGE';
    static SETTINGS_AUTO_LUNCH_CHANGE: string = 'SETTINGS_AUTO_LUNCH_CHANGE';

    static TRANSLATE_CLIPBOARD_TEXT: string = 'TRANSLATE_CLIPBOARD_TEXT';
};
